name: Deploy Safebloq to Streamlit Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest streamlit-testing
    
    - name: Run basic tests
      run: |
        python -c "import streamlit; print('Streamlit import successful')"
        python -c "import plotly; print('Plotly import successful')"
        python -c "import pandas; print('Pandas import successful')"
        
    - name: Test app startup
      run: |
        timeout 30 streamlit run app.py --server.headless true --server.port 8501 &
        sleep 10
        curl -f http://localhost:8501 || exit 1
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Deployment triggered on push to main branch"
        echo "Visit https://share.streamlit.io to connect your repository"
